/**
 * Parse the string into input parameters in Unix command-line style.
 * * Generated by gemini
 */
export function scanInput(s: string): string[] {
    const result: string[] = []
    let current = ""
    let i = 0

    // State tracking
    let inDoubleQuotes = false
    let inSingleQuotes = false
    let escaped = false // Whether currently in an escape state (\)

    while (i < s.length) {
        const char = s[i]!
        if (escaped) {
            // Current character is escaped, add directly and reset escape state
            current += char
            escaped = false
        } else if (char === '\\' && !inSingleQuotes) {
            // Backslash found, mark next character as escaped (no escape inside single quotes)
            escaped = true
        } else if (char === '"' && !inSingleQuotes) {
            // Toggle double quotes state
            inDoubleQuotes = !inDoubleQuotes
        } else if (char === "'" && !inDoubleQuotes) {
            // Toggle single quotes state
            inSingleQuotes = !inSingleQuotes
        } else if (/\s/.test(char) && !inDoubleQuotes && !inSingleQuotes) {
            // Space encountered outside quotes; push current buffer to result if not empty
            if (current.length > 0) {
                result.push(current)
                current = ""
            }
        } else {
            // Normal character
            current += char
        }
        i++
    }

    // Push the final segment
    if (current.length > 0) {
        result.push(current)
    }

    return result
}

/**
 * Format the console output, removing ANSI escape sequences (colors, cursor control, etc.) 
 * and keeping only plain text.
 * * Generated by gemini
 */
export function formatOutput(s: string): string {
    // This regex covers:
    // 1. CSI (Control Sequence Introducer) sequences: \x1b[...m (colors) or \x1b[...K (clear line), etc.
    // 2. OSC (Operating System Command) sequences: \x1b]...ST/BEL (e.g., changing window titles)
    // 3. Other 2-byte escape sequences
    const ansiRegex = [
        /[\u001b\u009b][[()#;?]*(?:[0-9]{1,4}(?:;[0-9]{0,4})*)?[0-4lnrmasqrABCDEFGHJKSTfipvz]/g,
        /\x1b\](([^\x07\x1b\x5c]*|(\x1b\\\x5c|[^\x1b\x5c])*)\x07|\x1b\x5c)/g,
        /\x1b[A-Z0-9]/g
    ]

    let result = s
    for (const re of ansiRegex) {
        result = result.replace(re, '')
    }

    return result
}